// generated by stringer -type=processtate; DO NOT EDIT

package prd

import "fmt"

const _processtate_name = "activewaitingForSendwaitingForReceiveterminated"

var _processtate_index = [...]uint8{0, 6, 20, 37, 47}

func (i processtate) String() string {
	if i < 0 || i+1 >= processtate(len(_processtate_index)) {
		return fmt.Sprintf("processtate(%d)", i)
	}
	return _processtate_name[_processtate_index[i]:_processtate_index[i+1]]
}
