// generated by stringer -type=Proces,Channel,processtate; DO NOT EDIT

package prd

import "fmt"

const _Proces_name = "goingForAWalkAliceGettingReadyBobGettingReady"

var _Proces_index = [...]uint8{0, 13, 30, 45}

func (i Proces) String() string {
	if i < 0 || i+1 >= Proces(len(_Proces_index)) {
		return fmt.Sprintf("Proces(%d)", i)
	}
	return _Proces_name[_Proces_index[i]:_Proces_index[i+1]]
}

const _Channel_name = "abc"

var _Channel_index = [...]uint8{0, 1, 2, 3}

func (i Channel) String() string {
	if i < 0 || i+1 >= Channel(len(_Channel_index)) {
		return fmt.Sprintf("Channel(%d)", i)
	}
	return _Channel_name[_Channel_index[i]:_Channel_index[i+1]]
}

const _processtate_name = "activewaitingForSendwaitingForReceive"

var _processtate_index = [...]uint8{0, 6, 20, 37}

func (i processtate) String() string {
	if i < 0 || i+1 >= processtate(len(_processtate_index)) {
		return fmt.Sprintf("processtate(%d)", i)
	}
	return _processtate_name[_processtate_index[i]:_processtate_index[i+1]]
}
